FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY common.hpp .
COPY p2.cpp .

RUN g++ -std=c++20 -O2 -I. p2.cpp -o p2 -lboost_system -lpthread

CMD ["./p2"]
